version: '3'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/postgres:/docker-entrypoint-initdb.d/
  task-manager:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: kaktas/task-manager
    ports:
      - "8080:8080"
    command: "./manager"
    depends_on:
      - postgres
    environment:
      - DRIVER_NAME=postgres
      - DATASOURCE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
  task-manager-react:
    build:
      context: ./web/app
      dockerfile: Dockerfile.dev
    image: kaktas/taskmanager-react
    volumes:
      - './web/app:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  postgres-data:
    driver: local